#!/bin/bash

S3_BUCKET=$1
S3_DATA_PATH=$2
DATA_FILENAME=$3

# upload data to s3
echo $S3_BUCKET
echo $S3_DATA_PATH
echo $DATA_FILENAME

aws s3 cp data/$DATA_FILENAME s3://$S3_BUCKET/$S3_DATA_PATH/$DATA_FILENAME
